In [5]:
# import json
# import os


# # Specify the directory path
# directory_path = '/Users/andreasnilsson/Library/CloudStorage/OneDrive-Nstart/Skrivbordet/Repository Homes/PSD2-Data-Engineering-Modeling-DATA-258-1/JSON'

# # Specify the filename
# filename = 'data.json'

# # Full path including the filename
# full_path = os.path.join(directory_path, filename)

# # Writing JSON data to a file in the specified directory
# with open(full_path, 'w') as file:
#     json.dump(data, file, indent=4)

In [10]:
import json
import os
import pandas as pd

# Specify the directory path
directory_path = '/Users/andreasnilsson/Library/CloudStorage/OneDrive-Nstart/Skrivbordet/Repository Homes/PSD2-Data-Engineering-Modeling-DATA-258-1/JSON'

# Specify the filename
filename = 'data.json'

# Full path including the filename
full_path = os.path.join(directory_path, filename)

# Reading JSON data back from the file
with open(full_path, 'r') as file:
    data_loaded = json.load(file)

# Print the data to verify it's been read correctly
print(data_loaded)

{'bankName': 'SWEDBANK', 'categories': [{'category': 'Gambling', 'count12Months': 157, 'count3Months': 61, 'count6Months': 102, 'count9Months': 115, 'monthlyAvg': 1598, 'partOfSalary12Months': 7.3, 'partOfSalary3Months': 19.8, 'partOfSalary6Months': 13.2, 'partOfSalary9Months': 8.3, 'sum12Months': 20779, 'sum3Months': 8848, 'sum6Months': 14498, 'sum9Months': 15567}, {'category': 'Crypto', 'count12Months': 0, 'count3Months': 0, 'count6Months': 0, 'count9Months': 0, 'monthlyAvg': 0, 'partOfSalary12Months': 0, 'partOfSalary3Months': 0, 'partOfSalary6Months': 0, 'partOfSalary9Months': 0, 'sum12Months': 0, 'sum3Months': 0, 'sum6Months': 0, 'sum9Months': 0}, {'category': 'MoneyRemittance', 'count12Months': 0, 'count3Months': 0, 'count6Months': 0, 'count9Months': 0, 'monthlyAvg': 0, 'partOfSalary12Months': 0, 'partOfSalary3Months': 0, 'partOfSalary6Months': 0, 'partOfSalary9Months': 0, 'sum12Months': 0, 'sum3Months': 0, 'sum6Months': 0, 'sum9Months': 0}, {'category': 'CashWithdrawal', 'count12Months': 32, 'count3Months': 7, 'count6Months': 13, 'count9Months': 19, 'monthlyAvg': 3424, 'partOfSalary12Months': 15.6, 'partOfSalary3Months': 13.6, 'partOfSalary6Months': 13.8, 'partOfSalary9Months': 11.1, 'sum12Months': 44514, 'sum3Months': 6114, 'sum6Months': 15214, 'sum9Months': 20914}, {'category': 'Gaming', 'count12Months': 0, 'count3Months': 0, 'count6Months': 0, 'count9Months': 0, 'monthlyAvg': 0, 'partOfSalary12Months': 0, 'partOfSalary3Months': 0, 'partOfSalary6Months': 0, 'partOfSalary9Months': 0, 'sum12Months': 0, 'sum3Months': 0, 'sum6Months': 0, 'sum9Months': 0}, {'category': 'MobilePayment', 'count12Months': 87, 'count3Months': 21, 'count6Months': 48, 'count9Months': 67, 'monthlyAvg': 4703, 'partOfSalary12Months': 21.4, 'partOfSalary3Months': 27.2, 'partOfSalary6Months': 26.4, 'partOfSalary9Months': 26.9, 'sum12Months': 61149, 'sum3Months': 12186, 'sum6Months': 29069, 'sum9Months': 50493}, {'category': 'DebtCollection', 'count12Months': 2, 'count3Months': 0, 'count6Months': 0, 'count9Months': 0, 'monthlyAvg': 585, 'partOfSalary12Months': 2.7, 'partOfSalary3Months': 0, 'partOfSalary6Months': 0, 'partOfSalary9Months': 0, 'sum12Months': 7608, 'sum3Months': 0, 'sum6Months': 0, 'sum9Months': 0}, {'category': 'InstallmentPayment', 'count12Months': 68, 'count3Months': 16, 'count6Months': 33, 'count9Months': 46, 'monthlyAvg': 18709, 'partOfSalary12Months': 85, 'partOfSalary3Months': 100, 'partOfSalary6Months': 130.1, 'partOfSalary9Months': 100.1, 'sum12Months': 243223, 'sum3Months': 44796, 'sum6Months': 143165, 'sum9Months': 188001}, {'category': 'HousingCost', 'count12Months': 13, 'count3Months': 3, 'count6Months': 7, 'count9Months': 10, 'monthlyAvg': 6166, 'partOfSalary12Months': 28, 'partOfSalary3Months': 45.8, 'partOfSalary6Months': 37.2, 'partOfSalary9Months': 32.5, 'sum12Months': 80166, 'sum3Months': 20512, 'sum6Months': 40952, 'sum9Months': 60983}, {'category': 'DirectDebit', 'count12Months': 0, 'count3Months': 0, 'count6Months': 0, 'count9Months': 0, 'monthlyAvg': 0, 'partOfSalary12Months': 0, 'partOfSalary3Months': 0, 'partOfSalary6Months': 0, 'partOfSalary9Months': 0, 'sum12Months': 0, 'sum3Months': 0, 'sum6Months': 0, 'sum9Months': 0}, {'category': 'Unclassified', 'count12Months': 963, 'count3Months': 401, 'count6Months': 694, 'count9Months': 852, 'monthlyAvg': 13067, 'partOfSalary12Months': 59.4, 'partOfSalary3Months': 174.3, 'partOfSalary6Months': 115.7, 'partOfSalary9Months': 81.1, 'sum12Months': 169881, 'sum3Months': 78082, 'sum6Months': 127374, 'sum9Months': 152291}], 'countryCode': 'SE', 'monthCount': 14, 'reportId': '00000000-0000-0000-0000-000000000000'}

In [12]:
pd.DataFrame(data_loaded)

,bankName,categories,countryCode,monthCount,reportId
0,SWEDBANK,"{'category': 'Gambling', 'count12Months': 157,...",SE,14,00000000-0000-0000-0000-000000000000
1,SWEDBANK,"{'category': 'Crypto', 'count12Months': 0, 'co...",SE,14,00000000-0000-0000-0000-000000000000
2,SWEDBANK,"{'category': 'MoneyRemittance', 'count12Months...",SE,14,00000000-0000-0000-0000-000000000000
3,SWEDBANK,"{'category': 'CashWithdrawal', 'count12Months'...",SE,14,00000000-0000-0000-0000-000000000000
4,SWEDBANK,"{'category': 'Gaming', 'count12Months': 0, 'co...",SE,14,00000000-0000-0000-0000-000000000000
5,SWEDBANK,"{'category': 'MobilePayment', 'count12Months':...",SE,14,00000000-0000-0000-0000-000000000000
6,SWEDBANK,"{'category': 'DebtCollection', 'count12Months'...",SE,14,00000000-0000-0000-0000-000000000000
7,SWEDBANK,"{'category': 'InstallmentPayment', 'count12Mon...",SE,14,00000000-0000-0000-0000-000000000000
8,SWEDBANK,"{'category': 'HousingCost', 'count12Months': 1...",SE,14,00000000-0000-0000-0000-000000000000
9,SWEDBANK,"{'category': 'DirectDebit', 'count12Months': 0...",SE,14,00000000-0000-0000-0000-000000000000
10,SWEDBANK,"{'category': 'Unclassified', 'count12Months': ...",SE,14,00000000-0000-0000-0000-000000000000